# fly.toml app configuration file generated for rails-articles-stripe on 2023-04-27T17:35:32-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rails-articles-stripe"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
